### PR TITLE
:bug: Make app versions consistent

### LINKED ISSUE #13: Inconsistent Version Numbers in Tauri
The package version in tauri.conf.json:

https://github.com/ProjectBlackPearl/pbpl/blob/c665f8190f8f752b84a1841b2ef0075bb1efbea5/src-tauri/tauri.conf.json#L9-L12

is conflicting with Cargo.toml:

https://github.com/ProjectBlackPearl/pbpl/blob/c665f8190f8f752b84a1841b2ef0075bb1efbea5/src-tauri/Cargo.toml#L1-L4

### PR DESCRIPTION
**Pull request by infinity-plus**
Closes #13 .

### CODE REVIEW

**Comment by Brisolo32** [comment]
Cargo.toml and package.json versions are different, otherwise LGTM

**Review by Brisolo32 — APPROVED** [review]
package.json and Cargo.toml "version" keys are different, one is 0.3.0 and the other is 0.2.0. Otherwise, LGTM

**Comment by infinity-plus** [comment]
> package.json and Cargo.toml "version" keys are different, one is 0.3.0 and the other is 0.2.0. Otherwise, LGTM

Thanks for pointing out

**Comment by infinity-plus** [comment]
> package.json and Cargo.toml "version" keys are different, one is 0.3.0 and the other is 0.2.0. Otherwise, LGTM

Thanks for pointing out

**Pull request merged**
